baseURL = "https://www.bostjankamnik.com/"
languageCode = "en-us"
title = "Kamnik Boštjan"

# navigation
[menu]
    # [[menu.main]]
    # name = "About"
    # URL = "about"
    # [[menu.main]]
    # name = "Blog"
    # URL = "blog"
    [[menu.main]]
    name = "Contact"
    URL = "contact"
    [[menu.main]]
    name = "Portfolio"
    URL = "portfolio"
    

[params]
home = "Home" # What you want the homepage to show up as in the menu bar
featuredProjectsCount = 6
