baseURL = "https://www.boka-place.com/"
languageCode = "en-us"
title = "Portfolio | Kamnik Boštjan"
theme = ""

# navigation
[menu]
    # [[menu.main]]
    # name = "About"
    # URL = "about"
    # [[menu.main]]
    # name = "Blog"
    # URL = "blog"
    [[menu.main]]
    name = "Contact"
    URL = "contact"
    [[menu.main]]
    name = "Portfolio"
    URL = "portfolio"
    

[params]
home = "Home" # What you want the homepage to show up as in the menu bar
# Meta data
description = "Portfolio Kamnik Boštjan"
author = "Boštjan Kamnik"
featuredProjectsCount = 6

  [params.contact]
  formAction = "https://formspree.io/f/xvodvwyd" # Add your formspree URL here to get emails

  # This contains the contact information for the footer
  [params.footer]
  email = "mkamnikbostjan@gmail.com"
  address = "Slovenj Gradec, Slovenia"
#   googlemaps = "https://www.google.com/maps/embed/v1/place?q=place_id:ChIJwbHYJaUqfEgRK0Ui9dVGimc&key=AIzaSyAE_4rVAKux_DSPcb_OdSRDaovtPOSk_3U"
